### ISSUE TITLE
Compiler error on Paradigm.csd

### ISSUE THREAD

**Issue by wyan** [micah-frank-studio/Lore#1]
When trying to compile or run Paradigm from either CSoundQt or the `csound` CLI I get the following error:

```
error: syntax error, unexpected T_IDENT, expecting T_OPCODE or T_FUNCTION or ',' or '='  (token "cabbageGet") from file Paradigm.csd (1)
 line 58:
>>>iXYPadBounds[] cabbageGet <<<
Parsing failed due to invalid input!
```

and the compilation fails.

I'm running on macOS 12 beta 6 on a Macbook Air M1 (2020).

**Comment by adeleglise** [comment]
I can confirm the same issue here. 

Running CsoundQt 0.10.0 on arch linux.

**Comment by micah-frank-studio** [comment]
Indeed, those Cabbage opcodes can only be compiled in [Cabbage](https://cabbageaudio.com/) as they are part of the UI. Seeing if @rorywalsh has a solution.

**Comment by rorywalsh** [comment]
Hi guys, it would be a bit of work to get this going in CsoundQT, but possible. You would need to replace the UI with widgets provided by CsoundQT. and then replace all `cabbageSet/Get` stuff with calls to `chnget/chnset`. THere aren't that many widgets in this instrument so it would definitely be possible, but a bit of work. 

To create a vanilla Csound version you can remove all the UI stuff and replace the channels with static values. This could be swapped out for MIDI controls once you have the basic build going. For example, `chnget:k("Pulses")` would be replaced with a variable such as `kPulses`. Again, a bit of work, be doable.

**Comment by micah-frank-studio** [comment]
If there's enough interest perhaps I should publish versions that don't depend on Cabbage - that just randomly control the params that are affected by the GUI. 

In the the meantime I'll put a note that it should only be compiled in Cabbage.

**Comment by adeleglise** [comment]
As I have little to no knowledge of Csound it would indeed be great if you provide stripped down version of this @micah-frank-studio 
However, thanks for providing those informations @rorywalsh !

**Comment by rorywalsh** [comment]
@adeleglise If you have little knowledge of Csound, why not simply run this code in Cabbage. That way you won't have to change a thing.

**Comment by adeleglise** [comment]
I can confirm that it loads fine with Cabbage.

**Comment by rorywalsh** [comment]
You're through the looking glass now 🤣

**Comment by wyan** [comment]
The only thing preventing me from running it in Cabbage is Cabbage crashing on M1 macs... hopefully that'll get solved 😅

**Comment by rorywalsh** [comment]
I've been running the latest beta version here without any problem on my M1
Mac Mini? You can grab installers here:

https://dev.azure.com/rorywalsh/cabbage/_build/results?buildId=1856&view=artifacts&pathAsName=false&type=publishedArtifacts

Might be best to do a separate install of the latest Csound, as I'm not
sure the version that ships with Cabbage is up to date..
