### ISSUE TITLE
build 1.0.24 does not work

### ISSUE THREAD

**Issue by ListeningGarden** [micah-frank-studio/Lore#11]
hey all,

i just grabbed build 1.0.24 to play around with the new ghost echo feature, but the build itself seems to be completely broken. it will not load audio from a file to play it, nor will it process audio through the input feature directly from a daw. almost all of the windows and dropdowns appear to be nonfunctional as well - the effects tab simply shows a blank list of "item" names, the samplers do not show any graphs, and so on
![Cabbage_Gci20DqTXD](https://user-images.githubusercontent.com/36242661/195945070-95c87551-cd24-4925-8cea-e5532b074861.png)

![2rLA4BKT5p_cropp](https://user-images.githubusercontent.com/36242661/195945095-249c3be1-4b91-4c95-bce4-5bacc34520c9.png)

i experience the issue loading the latest build available through github, directly loaded into cabbage as well as any standalone/vst builds. happy to provide any additional help/testing/info if needed!

**Comment by micah-frank-studio** [comment]
Ah - be sure to grab the latest Cabbage Build and let me know!
https://dev.azure.com/rorywalsh/cabbage/_build/results?buildId=2443&view=artifacts&pathAsName=false&type=publishedArtifacts

**Comment by ListeningGarden** [comment]
updated to the latest installer at that link as i was still using the public build (2.8.0) and lore itself now loads and process audio properly, _but_ unfortunately not completely out of the woods yet! whenever i try to load ghostecho, it crashes lore. this happens when running through cabbage directly or with a standalone/vst build

**Comment by nlajh** [comment]
I compiled Lore 1.0.24 with Cabbage 2.8.145 (that I got through Micah's link), and also experienced the issue reported by ListeningGarden that Lore crashes when selecting **GhostEcho**. Issue seems to me in **EffectsManager.orc**.

**REPLACING**

instr 10, Empty
endin

instr 11, Cassette
endin  

instr 12, Particle
endin   

instr 13, Cassette
endin

instr 14, ImpulseVerb
endin

**BY**

instr 10, Empty
endin

instr 11, Cassette
endin  

instr 12, Particle
endin   

instr 13, FilterVerb
endin

instr 14, ImpulseVerb
endin

instr 15, Scrambler
endin

instr 16, GhostEcho
endin

seems to solve the issue. 
Good luck!

**Comment by micah-frank-studio** [comment]
@nlajh @ListeningGarden Hey - so sorry for the delay here - my inbox is just impossible these days 😫
Oh, yeah, how are you updating? Did I not push EffectsManager.orc to the repo? 
Yep - that seems to be it - will push it again.... sorry!

`but are not loaded when I select one after -I think- the seventh entry from that LoV. I suppose I have to add them manually to ImpulseTables.orc (and maybe even need to recompile Lore for that?), but it would be nicer ofcourse when Lore would make a list automatically/dynamically, and/or would offer a browse function to an IR file (or similar: (LFO) wavetable when Lore may support that). `

Yes, I think the IRs might be fixed and predetermined in the code - let me see if I can make the system more flexible.

**Comment by ListeningGarden** [comment]
hey, @micah-frank-studio no worries! things have been a bit hectic here as well.

i've downloaded the updated files from the repo and attempted to render the file as a vst to load into my daw as before. bitwig is unable to load the vst and silently produces an error preventing it from being visible. the error log produced reports the following:

```
...\VST3\lore\lore.vst3

com.bitwig.flt.library.metadata.reader.exception.CouldNotReadMetadataException: could not read metadata: Not a plug-in file
```

i have downloaded newer versions of the cabbage nightlies, but no build seems to fix the issue

**Comment by NFATR** [comment]
I've had the same issue as ListeningGarden, Reaper is scanning Lore.vst3 on opening but it's not appearing in plugin window and is repeatedly showing in the "failed to scan" dropdown in plugin menu. 

Previous to updating cabbage build, I exported and it scanned fine, ran as plugin but wouldn't load audio files or display any input signal.

**Comment by NFATR** [comment]
> 

Update: Works perfectly as an AU, issues is just with VST and VST3.

**Comment by micah-frank-studio** [comment]
@NFATR @ListeningGarden 
Are we on Windows or OSX? 
I've tested it in Reaper in Windows and I cannot find any issues...
If you are on OSX it could be signing issue? 🤷‍♂️

**Comment by ListeningGarden** [comment]
@micah-frank-studio i'm testing on windows, just to clarify

i have pulled today's update 1.0.27 and have successfully built and loaded as vst/vst3 in bitwig, so i'm going to go ahead and put this issue to rest. thank you 💗
