### ISSUE TITLE
lore design issues with font and dpi

### ISSUE THREAD

**Issue by ListeningGarden** [micah-frank-studio/Lore#14]
hey again,

i meant to raise this issue last update, but as of 1.0.25, the font in lore has become very uncomfortable to view. i run a 24" 1440p monitor, so i do not have the benefit of a higher resolution and scaling to polish up text at the very small resolution that lore renders at 

![BitwigPluginHost-X64-SSE41_1DfxYeSlFZ](https://user-images.githubusercontent.com/36242661/207730140-2d53718a-57c0-4f4b-ae11-4118cba943ea.png)

i noticed this was the result of commit 4bf4687d70dec57c33da306ddbc1852977aba40f which actually fixed a bug where the intended font was not loading. though i can just delete the line about the font myself from the source, it would make more sense to find a more generalized solution that will work better for all use cases and not require patrons and people who bought subs directly from puremagnetik to have to figure out how to manually fix it and recompile their own versions

**_what should be done?_**

1.) lore should utilize fonts that specialize in readability in both low and high resolution scaling. either removing the custom font altogether so it defaults to one's system font (which it was doing by accident before) or by finding a free-to-use font that doesn't become so grainy at lower resolutions/dpi. i have tested with [inter](https://fonts.google.com/specimen/Inter?preview.size=16) and [source sans pro](https://fonts.google.com/specimen/Source+Sans+Pro?preview.size=16) as examples and found both to look pretty good, though different from inconsolata

2.) lore should be resizable. if that's not possible (i'm unfamiliar with the cabbage framework's limitations), then it should be made to be at least 25-50% bigger than it currently is. though this route is a lot more work, when i look at the roadmap i feel this will be important to do sooner rather than later, as adding more buttons as lore becomes more feature-rich and matured is going to cause the cramping issue to rear its head more and more

changing lore's size will certainly be a much larger undertaking since every element is given a hardcoded location, but i think it should still be in consideration for an update down the line, while switching the font can be a pretty quick fix at least for the time being

**Comment by micah-frank-studio** [comment]
Thanks for the notes. On windows this is definitely more of an issue. I
simply disable the custom font on the official windows distribution.

I will need to ask @rorywalsh about resizing a cabbage window and font
scaling. Not sure how we can make that work without a complete UI overhaul.
Fwiw, I don’t plan to cram any more controls into the UI. We also might opt
for a Lore 2.0 that is paneled with fewer controls in view at a time.

**Comment by rorywalsh** [comment]
Hi @micah-frank-studio Have you tried the window resizing mechanism? The following code will place a combobox onto the UI that users can use to control instrument resizing. 

`combobox bounds(10, 180, 80, 20), mode("resize"), value(3)`

The last selected size will be saved with the user session.

**Comment by micah-frank-studio** [comment]
OK, I've thinking to have a preferences window. This might be the place to do it.

**Comment by rorywalsh** [comment]
Are you trying this within a plugin? It only works in plugins, not standalones..

**Comment by micah-frank-studio** [comment]
Oh I just tried it within cabbage.

**Comment by micah-frank-studio** [comment]
We now have Light/Dark UI modes and window scaling, new fonts and a few other details...
