### ISSUE TITLE
How to avoid 64 inputs/outputs when compile

### ISSUE THREAD

**Issue by nay-seven** [micah-frank-studio/Lore#2]
Hello,
a bug and a question,

I compile Lore with cabbage and I end up with a vst plugin with 64 inputs/outputs, I would like to have just one input/output stereo is it possible? ( btw, (the input is not used for the moment, right? )
In my Daw (Usine hollyhock) Lore don't work and maybe these inputs/outputs are the reason ?
( works in other Daw's like Bespoke)
I looked in the code, but nothing obvious to me ;-)
thanks

**Comment by micah-frank-studio** [comment]
My apologies this issue was never followed up on. Can it be closed or is it still relevant?
