### ISSUE TITLE
Particles crash Lore last version

### ISSUE THREAD

**Issue by nay-seven** [micah-frank-studio/Lore#4]
Hello,
I compile last  Lore ( 12 h ago with [fixed persistency issue) with Cabbage ( vst and standalone)
both crash when i select particles
i join the cabbage console, there's some some warnings about Effects.orc
[lore cabbage console.rtf.zip](https://github.com/micah-frank-studio/Lore/files/8876330/lore.cabbage.console.rtf.zip)

MacOs Mojave here

**Comment by nay-seven** [comment]
yes, only Particle, last try this morning in Bespoke, freeze the plugin

**Comment by micah-frank-studio** [comment]
Hi - is this still an issue with the latest Cabbage/Lore?
