### ISSUE TITLE
silicon compatibility

### ISSUE THREAD

**Issue by postprivee** [micah-frank-studio/Lore#6]
hi Micah!
Ive bought almost all of your plugins + subscribed to Lore. they're all very creative+inspiring. thanks for all your hard work!
however, I'd like to ask if you can release M1 compatible installers without Rosetta requirement. I guess it wouldn't work for Lore due to Cabbage dependency. just wanted to make sure if thats the case. 
thanks

**Comment by postprivee** [comment]
all native silicon

Lore
Antoka
Bitfight83
Cloudmaster
Clusters
Darklands
Fog
Foomph
Fusia
Nighthawk
Octavlord
Partikl
Pastfabric
Rust
Speektra
Shrike
Swarm
TheBarber
Vanisher
Weave
Zerone

**Comment by micah-frank-studio** [comment]
Oh sorry I just saw this. Yep everything’s now native m1
