### ISSUE TITLE
The values of frequency bars (FILTER/TIME/FBACK) are not being saved/loaded.

### ISSUE THREAD

**Issue by yaremenko8** [micah-frank-studio/Lore#9]
LORE 1.0.22
LORE fails to store/retrieve information about the values of FILTER/TIME/FBACK bars.
Scenarios:
1. Options --> Load a saved state...
2. Saving and loading LORE as a preset in DAW.

**Comment by micah-frank-studio** [comment]
Indeed - working to fix this

**Comment by micah-frank-studio** [comment]
This should be solved now.
